import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useForm } from 'react-hook-form'
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { register, handleSubmit, watch, formState: { errors } } = useForm();
  const [ loading, setLoading ] = useState(false);
  const [ outputHtml, setOutputHtml ] = useState("output.html");
  const [ outputCode, setOutputCode ] = useState("<html>ここにコードが出力されます</html>");

  return (
    <>
      <Head>
        <title>GPH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>HTMLジェネレーター</h1>
        <form onSubmit={handleSubmit(async (features) => {
          setLoading(true);
          const res = await fetch('/api/feature', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify(features),
          });
          const data = await res.json();
          console.log(data);
          setOutputHtml(data.path);
          setOutputCode(data.code);
          setLoading(false);
        })}>
          <label>欲しい機能を入力してください。</label>
          <div>
            <textarea style={{"width": "90%", "height": "50px"}} {...register("feature", { required: true })} />
          </div>
          <div>
            <input type="submit" />
          </div>
        </form>
        { loading && <span className={styles.loading}></span>}
        <iframe src={outputHtml} width="100%" height="800px" />
        <pre>
          <code>{outputCode}</code>
        </pre>
      </main>
    </>
  )
}
